### ISSUE TITLE
About the Joint Training.

### ISSUE THREAD

**Issue by leon0n** [backseason/PoolNet#1]
HI, guy. Thanks for your project. I read this code, but i didn't find any code for the Joint Training for the Edge. Could you please tell me, which line represent the joint training, and how the 2 loss merge?

**Comment by houqb** [comment]
Thanks for your attention. The code at this point contains nothing about joint training with edge detection. We will release that part in the coming days.

**Comment by backseason** [comment]
The codes for joint training with edge has been released. You may have a try.
