### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PoolNet

### ISSUE THREAD

**Issue by farazBhatti** [backseason/PoolNet#10]
Hi, i am to trying to run it to test some images but keep getting this error when using cpu for inference

**Comment by backseason** [comment]
Pls provide more detailed information.

**Comment by farazBhatti** [comment]
using python3, torch1.1.0 .ubuntu 18

error comes when loading the trained resnet or vgg model

error = 'RuntimeError: Error(s) in loading state_dict for PoolNet:
	Missing key(s) in state_dict: "base.resnet.conv1.weight", "base.resnet.bn1.weight", "base.resnet.bn1.bias", "base.resnet.bn1.running_mean", "base.resnet.bn1.running_var", "base.resnet.layer1.0.conv1.weight...",'.

I have tried the following  solutions with no luck:
https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686
tried updating line 28 of code file solver.py
from this
            self.net.load_state_dict(torch.load(self.config.model))
to this 
            self.net.load_state_dict(torch.load(self.config.model,map_location='cpu'))

i want to do inference using cpu.
Thanks

**Comment by backseason** [comment]
I think it might because that the pretrained model was stored with `DataParallel` mode, if the `Unexpected key(s)` include some items begin with `module.`
You may have a try of this: https://discuss.pytorch.org/t/solved-keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict/1686/13
Hope it helps.

**Comment by farazBhatti** [comment]
updated solver.py as recommended
`class Solver(object):

            
            print('Loading pre-trained model from %s...' % self.config.model)
            #self.net = nn.DataParallel(self.net) 
            state_dict = torch.load(self.config.model, map_location=lambda storage, location: storage)
	        
            new_state_dict = OrderedDict()
            for k,v in state_dict.items():
                
                name = k[7:]
                new_state_dict[name]=v

            # original saved file with DataParallel
            
            # create new OrderedDict that does not contain `module.`
            self.net.load_state_dict(new_state_dict)
            self.net.eval()`

`

and still getting error
`RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict: "module.base.resnet.conv1.weight", "module.base.resnet.bn1.weight", "module.base.resnet.bn1.bias", "module.base.resnet.bn1.running_mean", "module.base.resnet.bn1.running_var", "module.base.resnet.layer1.0.conv1.weight",.......`

**Comment by backseason** [comment]
I have modify the codes to support cpu mode, pls have a pull.
During testing, add and extra `--no-cuda` arg, and it works on my local machine.

**Comment by farazBhatti** [comment]
I dont know what i am doing wrong, it is still not working.here is the new error :

`Loading pre-trained model from None...

AttributeError: NoneType object has no attribute 'seek'. You can only torch.load from a file that is seekable. Please pre-load the data into a buffer like io.BytesIO and try to load from it instead.'.

I feel there is a little misunderstanding here, (i might be wrong),
on Read me page you have  [mentioned](https://github.com/backseason/PoolNet#3-download-the-pre-trained-models-for-backbone) to put pre-trained models for backbone into data/pretrained folder

but in code (main.py,line-54) it is [mentioned](https://github.com/backseason/PoolNet/blob/07635a922dabe78b8f0b49f9ca852e2687f55200/main.py#L54) `    resnet_path = './dataset/pretrained/resnet50_caffe.pth'
`.
well offcourse ive downloaded into folder according to code. but for pretrained PoolNet-ResNet50 w/ edge, i am a little confused to where to put [this mode](https://github.com/backseason/PoolNet#6-pre-trained-models-pre-computed-results-and-evaluation-results) as i ve missed somehow where you have mentioned

**Comment by farazBhatti** [comment]
Thanks @backseason , it worked like charm.....
it shouldn't be much of a concern but [here](https://github.com/backseason/PoolNet#3-download-the-pre-trained-models-for-backbone) is a slight typo. it should be ./dataset/pretrained/.

**Comment by aishetty** [comment]
HI, I am still getting the same error. I pulled the latest commit and tried testing with --no-cuda. 

Error is 
RuntimeError: Error(s) in loading state_dict for PoolNet:
        Missing key(s) in state_dict: "base.resnet.conv1.weight", "base.resnet.bn1.bias", "base.resnet.bn1.

The command I have used is 
python main.py --mode='test' --model='dataset/pretrained/vgg16_20M.pth' --test_fold='results/' --sal_mode='e' --no-cuda

Where am I going wrong? Kindly assist me on this.

**Comment by farazBhatti** [comment]
@aishetty have you tried not adding this argument in command line "--no-cuda"..

**Comment by aishetty** [comment]
The command I have used is
python main.py --mode='test' --model='dataset/pretrained/vgg16_20M.pth' --test_fold='results/' --sal_mode='e' --no-cuda

I have used it. But Still I get the error

**Comment by aishetty** [comment]
If I dont use --no-cuda, 
I get the error
**AssertionError: Torch not compiled with CUDA enabled**

**Comment by backseason** [comment]
You're getting this error because the pretrained model `vgg16_20M.pth` only contains init params for the VGG16 backbone.
For testing, use pretrained model in https://github.com/backseason/PoolNet#6-pre-trained-models-pre-computed-results-and-evaluation-results .

**Comment by aishetty** [comment]
Yes, It worked after this change. Thanks
