### ISSUE TITLE
Interesting Work

### ISSUE THREAD

**Issue by HoracceFeng** [backseason/PoolNet#13]
Hi @backseason,

I got some introduction about this work from here https://mp.weixin.qq.com/s?__biz=MzIwMTc4ODE0Mw==&mid=2247497352&idx=1&sn=dff7e64e7d388fbb394d6f7c81a544bc&chksm=96ea2908a19da01edc1697644be521b818e08625e13d20aff91aa350e8a8197fb963e84eaf9e&scene=0&xtrack=1#rd . 

The idea is simple yet effective, thanks for your work. My question is, have you tried to implement FAM as a refinement of FPN in those SOTA detection algorithms like yolov3 or retinanet? I think the FAM should be useful in detection also.

**Comment by backseason** [comment]
Thanks!
We haven't tried this on other vision tasks. 
You may give it a try, and it should be simple to plug FAM into other frameworks as there are many open source PyTorch-based detection implementations.
Good luck!
