### ISSUE TITLE
Network structure question

### ISSUE THREAD

**Issue by creabob** [backseason/PoolNet#16]
There are some classes ConvertLayer,DeepPoolLayer,ScoreLayer and base in networks/PoolNet.py .I want to know these classes correspond to which module refering to paper,for example GGM module,FAM module and Edge Detection module.

**Comment by backseason** [comment]
Sorry for the miss leading.
`ConvertLayer` is for channel decreasing and `DeepPoolLayer` refers to FAM.
`ScoreLayer` is a 1x1 conv to get the final prediction map while `base` includes the backbone and GGM.

I think if you have read the paper and code you can figure these relations out quickly. Good luck!
