### ISSUE TITLE
Could you provider the evaluation code?

### ISSUE THREAD

**Issue by thb1314** [backseason/PoolNet#19]
I evaluated the test results using usual method.
I find that MAE score is closed to your conclusion while the value of **MaxF** is far from your's
So,Could you provider the evaluation code?
Thank you

**Comment by backseason** [comment]
Duplicate of #6

**Comment by zwm19950414** [comment]
thb1314，Will you get the same results as the article if you check the MAE of the article? If so, can you share the code you got for MAE?Why do I check your vgg16 results(MAE) and your article is not correct (such as ECSSD I measured 0.081421 and yours is 0.044, PASCAL I measured 0.119801 and yours is 0.072), is this too bad? More, of course, I tested your resnet50 is OK (such as ECSSD I measured 0.038383 and your article is 0.038, PASCAL I measured 0.075219 and your article is 0.065),
