### ISSUE TITLE
about test

### ISSUE THREAD

**Issue by KaaiLee** [backseason/PoolNet#2]
hi,thanks  for your project.Ｉs it only possible to test with public datasets in your project? If I want to test with my own dataset, what should I do?

**Comment by backseason** [comment]
1. Prepare your images under one folder X and generate the corresponding .lst file Y.
2. Set the 'image_root' and 'image_source' params in the 'main.py' file to X and Y.
3. At test time set the '--sal_mode' param to your image settings.
