### ISSUE TITLE
Training your own database

### ISSUE THREAD

**Issue by leiyaohui** [backseason/PoolNet#20]
Dear author,

Thanks for your great work !

How can I make my own database and train on it?

Thank you !

**Comment by backseason** [comment]
The training data is formed up in Caffe style.
You can store your training image and groundtruth inside one folder and generate a list file to point to the locations of these files. 
You may refer to the `data/msrab_hkuis/msrab_hkuis_train_no_small.lst` file in https://github.com/backseason/PoolNet#2-download-the-datasets for example.
After setting the `--train_root` and `--train_list`  parameters in `train.sh` correctly, you shall be able to run.
