### ISSUE TITLE
A quesion about the arch of resnet50

### ISSUE THREAD

**Issue by hideonInternet** [backseason/PoolNet#22]
https://github.com/backseason/PoolNet/blob/cf8ae8f5bc7a4a894f6d8755b5475e7856a253d2/networks/deeplab_resnet.py#L104

Hi, would you like to tell why you set `ceil_mode` to `True`? is it that a trick to get better performance or some other reason?

**Comment by backseason** [comment]
It's a simple copy of https://github.com/isht7/pytorch-deeplab-resnet/blob/839bdcec7814be52498f2c22b1020d7d2e9f4d16/deeplab_resnet.py#L134

**Comment by hideonInternet** [comment]
Thanks
