### ISSUE TITLE
Can you provide the pre-computed saliency maps?

### ISSUE THREAD

**Issue by ShuhanChen** [backseason/PoolNet#23]
Can you provide the pre-computed saliency maps, both vgg and resnet version?

**Comment by backseason** [comment]
We have provided the resnet-50 version over here: https://github.com/backseason/PoolNet#6-pre-trained-models-pre-computed-results-and-evaluation-results

**Comment by ShuhanChen** [comment]
Thanks, I found it. BTW, can you also provide the vgg version?

**Comment by ShuhanChen** [comment]
There are two images missing on DUT-OMRON: sun_akxddynsopjifavt.jpg and sun_barwtmnxkuxyttlj.jpg, can you check?

I also found the max F results on DUT-OMRON reported in the paper are different with other papers, such as PiCANet_resnet-50 is 0.803 in paper CPD CVPR19, which is lower than 0.820 as shown in your paper. I also used your provided saliency maps and SalMetric, and only got 0.805, which is also lower than 0.833. Can you tell me why? Thanks.

**Comment by ZhangC2** [comment]
Are the provided the pre-computed saliency maps  resnet-50 version? I think they are the VGG version.  I evalute the results generated by the provided resnet50-model (w/o edge), and i cannot get the simliar results reported in the paper.
