### ISSUE TITLE
实验模块分析

### ISSUE THREAD

**Issue by tuqiangwang** [backseason/PoolNet#24]
您好！
我仔细读了你们的实验部分，我有一点疑问，就是你们的FAM模块和图1中的F模块，实验效果是否和这两者的个数和位置有关？

**Comment by backseason** [comment]
我们没有关于FAM的个数和位置做具体的分析实验，没有以此作为paper的重点部分。
关于实验效果，我们认为这与FAM个数肯定是有关系的。
FAM是设计用来消除由于不同特征之间的感受野跨度过大而导致的信息冲突而设计的，所以我们将其放置在跨尺度特征相加之后。
