### ISSUE TITLE
请问您的pretrained的模型所需要输入都是这么处理的么？

### ISSUE THREAD

**Issue by thb1314** [backseason/PoolNet#28]
您好，我看到您在code当中对resnet50和vgg16的dataset做了相同的处理，请问您提供的预训练模型是基于什么的比赛的么？我看网上流传的resnet50和vgg net 对数据预处理的方式不一样

**Comment by backseason** [comment]
VGG-16是直接使用的HED中提供的Caffe版本的预训练参数，ResNet-50也同样使用的Caffe版本的预训练参数；两种参数都不是基于什么比赛的，只是输入图像格式是BGR, [0-255]。
