### ISSUE TITLE
不好意思，我想再确认一下

### ISSUE THREAD

**Issue by thb1314** [backseason/PoolNet#29]
您说“VGG-16是直接使用的HED中提供的Caffe版本的预训练参数，ResNet-50也同样使用的Caffe版本的预训练参数；两种参数都不是基于什么比赛的，只是输入图像格式是BGR, [0-255]。”，然而我看代码中是减去一个均值的，这其中原因是什么呢？

**Comment by backseason** [comment]
现在的CNN输入图像的时候都要减去均值。

**Comment by thb1314** [comment]
那我想明确一下，就是现在“CNN输入图像的时候都要减去均值”，然后您使用的pretrained model他一开始train的时候是“输入图像格式是BGR, [0-255]”，是这样子么？

**Comment by backseason** [comment]
是的。

**Comment by thb1314** [comment]
好的，我没问题了，谢谢您，这个issue 我 close了
