### ISSUE TITLE
Run with a single Image

### ISSUE THREAD

**Issue by HHIR** [backseason/PoolNet#32]
Good result, but the big problem of code is written in a very confusing way.
for example, it is not easy to run code for just one image as the input and get one output!!! [ I mean not in the list file ] ...
Please give some guidance about running code with a single image. ( not from the list)

thank

**Comment by backseason** [comment]
You can follow the functions in `dataset/dataset.py` to load the image file into torch.Tensor.
And build the network as done in the `solver.py` file.
Then just forward the loaded tensor into the network to get the predictions.
It's easy and straightforward. Good luck!
