### ISSUE TITLE
I cannot get the similar results with provided resnet-50 (w/o edge) as repoted in paper

### ISSUE THREAD

**Issue by ZhangC2** [backseason/PoolNet#33]
I cannot get the similar results with provided resnet-50 (w/o edge run-0) as repoted in paper.

**Comment by backseason** [comment]
We evaluated all the results with the code provided [here](https://github.com/Andrew-Qibin/SalMetric).
I re-evaluated the results of ResNet-50 (w/o edge) and got identical scores.
Detailed scores are here.
[eval_results.txt](https://github.com/backseason/PoolNet/files/3907835/eval_results.txt)
