### ISSUE TITLE
Three image pairs in your DUTS.zip are not matched.

### ISSUE THREAD

**Issue by ysyscool** [backseason/PoolNet#34]
Hi, 

Thanks for your codes. I find that three image pairs (ILSVRC2014_train_00023530, n04442312_17818, n01532829_13482) in your DUTS.zip are not matched as your train_pair.lst.

**Comment by backseason** [comment]
Yes, some image and gt pairs are of different sizes in the DUTS-TR dataset, we simply ignore these pairs during training.
