### ISSUE TITLE
I am a little different about your vgg16 results, why

### ISSUE THREAD

**Issue by zwm19950414** [backseason/PoolNet#35]
Why do I check your vgg16 results and your article is not correct (such as ECSSD I measured 0.081421 and yours is 0.044, PASCAL I measured 0.119801 and yours is 0.072), is this too bad? More, of course, I tested your resnet50 is OK (such as ECSSD I measured 0.038383 and your article is 0.038, PASCAL I measured 0.075219 and your article is 0.065), can you explain?

**Comment by backseason** [comment]
I re-evaluated the provided pre-computed saliency maps with two differently implemented evaluation codes (both C++ and Python) and got identical scores to our paper.
![Screenshot from 2019-12-01 12-48-50](https://user-images.githubusercontent.com/7400760/69909659-7c572a00-1439-11ea-88d1-9e5a81e879e1.png)

**Comment by zwm19950414** [comment]
backseason，So, do you comment on this link you shared?https://github.com/Andrew-Qibin/SalMetric

**Comment by backseason** [comment]
Yes, the link I shared is the C++ version.
I also used a Python version implemented by other people and got the same MAE results, as in the screenshot above.

**Comment by zwm19950414** [comment]
Thank you for your answer, I have no problem
