### ISSUE TITLE
Precision_Recall Curves drawing

### ISSUE THREAD

**Issue by LoveSimons** [backseason/PoolNet#36]
Hello, I am very interested in your research direction. Thank you for sharing the code. I am a graduate student and my research direction is related to saliency target detection. Your idea is very novel. Can you share the code for PR curve drawing? I want to see the final effec，Looking forward to your reply, I wish you a happy life.

**Comment by backseason** [comment]
We used the code in this repo: https://github.com/Pchank/caffe-sal.
Hope it helps.

**Comment by LoveSimons** [comment]
Thanks


---Original---
