### ISSUE TITLE
BN

### ISSUE THREAD

**Issue by FENGShuanglang** [backseason/PoolNet#4]
Thanks for your project. I have read your code about PoolNet, i want to know why there is no Batch Normalization in your decoder ,eg. https://github.com/backseason/PoolNet/blob/ea18b1ef66a3c6a7db3f8affbab514059f2b4938/networks/poolnet_1task.py#L31

**Comment by backseason** [comment]
We only support batch_size=1. There is no need to use BN layer for such small batch size.

**Comment by FENGShuanglang** [comment]
This is a very noteworthy point if others want to use your code!

**Comment by backseason** [comment]
Thanks for your suggestion. :)
