### ISSUE TITLE
predction result

### ISSUE THREAD

**Issue by LoveSimons** [backseason/PoolNet#40]
Hello, thank you for sharing the code. I need to do a comparison experiment and want to compare with your algorithm, but I didn't find your model training results. Can you provide the test results on six data sets? If you can provide it, please share the download address of Baidu Web Disk. Looking forward to your reply, I wish you a happy life.

**Comment by backseason** [comment]
The pre-computed saliency maps are already provided here: https://github.com/backseason/PoolNet#6-pre-trained-models-pre-computed-results-and-evaluation-results

**Comment by LoveSimons** [comment]
Because I'm in China, downloading across the wall is slow. Can you provide Baidu web disk download address? Looking forward to your reply, I wish you a happy life.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiang-Jiang Liu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 中午12:57
收件人:&nbsp;"backseason/PoolNet"<PoolNet@noreply.github.com&gt;;
抄送:&nbsp;"guanlaifu"<351161991@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [backseason/PoolNet] predction result (#40)




The pre-computed saliency maps are already provided here: https://github.com/backseason/PoolNet#6-pre-trained-models-pre-computed-results-and-evaluation-results

**Comment by backseason** [comment]
I'm also in China. But actually it's much slower for me to use BaiduDisk.
Good luck!

**Comment by backseason** [comment]
Though I'm in China, it's really slow to use BaiduDisk. I believe that you'd find a way. Good luck!
