### ISSUE TITLE
请问为何ｌｏｓｓ值这么大但效果却很好

### ISSUE THREAD

**Issue by creabob** [backseason/PoolNet#42]
我在训练时采用ＤＵＴＳ－ＴＲ测试使用ＤＵＴＳ－ＴＥ，但是发现ｓａｌ　ｌｏｓｓ值在几千至一万，为何值这么大，但是测试时发现效果还不错。　为何不收敛却效果很好。并且在ｓｏｌｖｅｒ中的ｂｃｅ２ｄ（）函数是准备干嘛用的，和您使用的损失函数有何区别，谢谢！

**Comment by creabob** [comment]
![1581466408(1)](https://user-images.githubusercontent.com/25314080/74291354-7cf53080-4d99-11ea-8f6d-9463947e1900.jpg)

**Comment by backseason** [comment]
Loss值比较大而且波动是因为采用了sum而不是average mean。
bce2d()是给联合训练边缘检测任务使用的。

**Comment by creabob** [comment]
谢谢
