### ISSUE TITLE
训练加载 batchsize=1

### ISSUE THREAD

**Issue by gunerhui** [backseason/PoolNet#44]
您好，我想请问下数据训练时采用batchsize=1是因为，训练图片不一致导致的吗，这一块会不会影响收敛，我这边20以后收敛不理想

**Comment by backseason** [comment]
是的，因为输入图片的大小不一致。这一块不会影响网络的收敛。loss采用的是sum而不是mean，所以单从loss的绝对值并不能断定网络没有很好的收敛。

**Comment by gunerhui** [comment]
谢谢您的回复
