### ISSUE TITLE
Trained model with VGG16 backbone?

### ISSUE THREAD

**Issue by majinyu666** [backseason/PoolNet#49]
Hi, thanks for your great work.
I find that your run-2.zip does not include the trained model, i.e., run-2/models/final.pth. Could you please offer that? I want to test it on other datasets. Thank you!

**Comment by backseason** [comment]
Sorry, the pretrained model for VGG-16 is missing and I don't have a backup for it.
![image](https://user-images.githubusercontent.com/7400760/81939220-a176d800-9628-11ea-83c2-8c15ac17481b.png)

**Comment by majinyu666** [comment]
Much thanks to your  immediate reply! Sorry to hear that. So, if I decide to train VGG16 myself, could you offer detailed configurations like lr/lr_decay/batch_size ... or other noticable things? I would appreciate that. Thank you again.

**Comment by backseason** [comment]
You're welcome. 
`python main.py --arch vgg --train_root ./data/DUTS/DUTS-TR --train_list ./data/DUTS/DUTS-TR/train_pair.lst` should do the work.

**Comment by majinyu666** [comment]
Thank you. I will try it out.
