### ISSUE TITLE
Global Guidance Module 

### ISSUE THREAD

**Issue by ghost** [backseason/PoolNet#50]
I'm looking for the implementation of the Global Guidance Module. 
Is it released in the source/pretrained model already?

**Comment by backseason** [comment]
Yes, it's included in the source code. 
Taking the ResNet-50 version for example, the PPM is implemented around https://github.com/backseason/PoolNet/blob/06d06549b745418eb03ded4ba719fb83c9b57f32/networks/deeplab_resnet.py#L167, and the GGFs are around https://github.com/backseason/PoolNet/blob/06d06549b745418eb03ded4ba719fb83c9b57f32/networks/deeplab_resnet.py#L172.

**Comment by ghost** [comment]
Found it. Thanks!
