### ISSUE TITLE
About dataloader

### ISSUE THREAD

**Issue by GrassBro** [backseason/PoolNet#51]
Hi, @backseason ,

I utilize my own dataloader to train the network, where the image is resized and cropped to a fixed size. Therefore, I could use a large batch size, e.g., 32.  I wonder to know whether such an operation would influence the final performance?

Thx!

**Comment by backseason** [comment]
There is a big chance that the final performance will be influenced. But I'm not sure whether it's in a positive way. Some of the hyper-parameters should be fine-tuned accordingly.
