### ISSUE TITLE
请问模型训练时batch_size只能是1么？超过1会如何？

### ISSUE THREAD

**Issue by pengqianli** [backseason/PoolNet#52]

**Comment by backseason** [comment]
dataloader使用的图片为原始大小，所以batch_size只能为1。

**Comment by pengqianli** [comment]
感谢您的回复，也就是说，是显存大小限制了batchsize的大小了？（或者是因为考虑输入图片可能存在尺度不一样的情况？），不够怎么样，感谢答疑！

**Comment by backseason** [comment]
不是因为显存，只是为了保持测试时候可以接受任意尺寸的图片输入。当输入图片的尺寸不一样时，无法cat为一个tensor。

**Comment by pengqianli** [comment]
明白了，谢谢您！
