### ISSUE TITLE
Results are all black pictrures.

### ISSUE THREAD

**Issue by LitterWindwind** [backseason/PoolNet#55]
The images in the output predictive images folder are all black, but they vary in size, indicating that the prediction has been made. Do you know the cause of this problem?

**Comment by backseason** [comment]
I can hardly tell what the problem might be with the information you provided.
Please make sure you have followed the steps in the instruction strictly.

**Comment by DHW-Master** [comment]
I can not download your pre-trained model

**Comment by backseason** [comment]
> I can not download your pre-trained model

All the models are provided with both GoogleDrive and BaiduYun.
And I've rechecked that all the links are available now.

**Comment by zhaozhirui** [comment]
> The images in the output predictive images folder are all black, but they vary in size, indicating that the prediction has been made. Do you know the cause of this problem?

I have the same problem. Have you solved it？
