### ISSUE TITLE
预训练模型的百度云下载链接无法使用了

### ISSUE THREAD

**Issue by kaikaizhu** [backseason/PoolNet#57]
我想下载resnet50_caffe.pth，但是发现预训练模型的百度云下载链接失效了，能不能帮忙再上传一下，感谢！
或者有好心人帮忙发一下我的邮箱也可以 244558576@qq.com

**Comment by backseason** [comment]
谢谢提醒！
新的链接如下：链接: https://pan.baidu.com/s/1ehZheaqeU3pyvYQfRU9c6A 提取码: 27p5
