### ISSUE TITLE
About the evaluation

### ISSUE THREAD

**Issue by Pilhyeon** [backseason/PoolNet#6]
Hi.
First of all, I would like to thank you for this great work.
I have finished training the model on MSRA-B dataset, and observed the model works well on the test set.
However, I have a concern about the reliability of this model.
So, I want to evaluate this model. How can I do?
Thank you.

**Comment by backseason** [comment]
You may refer to this repo for results evaluation: https://github.com/Andrew-Qibin/SalMetric

**Comment by Pilhyeon** [comment]
Thank you!
I'll try it.
