### ISSUE TITLE
Different saliency predictions for the same images

### ISSUE THREAD

**Issue by AthaSSiN** [backseason/PoolNet#60]
Hi! I was trying to get saliency maps of some test images not from the 6 datasets. The issue that I am facing is that I am getting different predictions for the same image upon passing through the network. Upon checking I found that the value of preds being calculated by solver.py is not the same even for the same picture, and also is always somewhere near 0.5

This also leads to a nearly completely gray image being produced, and no salienct images as in the paper.
I am using the pretrained model trained on the edge detection dataset provided in google drive.

I was facing problem in loading the edge model as it seemed that a few keys were missing in it. So i loaded it as using load_pretrained_model, if that is relevant to this issue.

Looking forward to your prompt reply
Regards

**Comment by AthaSSiN** [comment]
![download2](https://user-images.githubusercontent.com/56124496/88457060-065c7300-cea1-11ea-96d7-354be5383c0a.png)
![download1](https://user-images.githubusercontent.com/56124496/88457066-0d838100-cea1-11ea-8af9-99f8a76b910f.png)

Here are the generated saliencies  (multi_fuse values) of the same images in 2 different iterations [They don't apper only gray due to auto scaling by matplot , but here are the values of multi_fuse[100] :  [127.40904  127.44184  127.47464  127.56405  127.65383  127.62597
 127.59653  127.61647  127.63743  127.6367   127.635345 127.63775
 127.64024  127.64205  127.643845 127.644104 127.64429  127.64257
 127.64075  127.64078  127.64093  127.63936  127.63767  127.635635
 127.6336   127.631714 127.62986  127.62828  127.62675  127.6248
 127.622795 127.62146  127.62019  127.61953  127.618935 127.617836
 127.616684 127.61618  127.61578  127.620834 127.626656 127.63678
 127.64757  127.64922  127.64939  127.65561  127.66287  127.67415
 127.68614  127.73446  127.78977  127.812935 127.82963  127.824684
 127.81517  127.81151  127.809135 127.852135 127.90564  127.92208
 127.92957  127.91235  127.8889   127.92223  127.97046  127.947205
 127.9044   127.86364  127.823456 127.80114  127.78412  127.74109
 127.69011  127.667175 127.65319  127.64697  127.643326 127.63909
 127.634636 127.631775 127.62948  127.62848  127.62793  127.62549
 127.62228  127.61855  127.61463  127.61267  127.6115   127.61053
 127.609634 127.6093   127.60918  127.607704 127.60564  127.60366
 127.60173  127.60158  127.60229  127.60009  127.59645  127.59464
 127.59378  127.592545 127.59113  127.58972  127.58831  127.5879
 127.588036 127.58802  127.58793  127.5881   127.58843  127.58855
 127.58855  127.58862  127.588745 127.58954  127.59077  127.59217
 127.59369  127.59501  127.596214 127.597015 127.597565 127.59896
 127.60097  127.6021   127.60256  127.60349  127.60477  127.604935
 127.60425  127.604126 127.60445  127.6034   127.60121  127.59986
 127.599205 127.60025  127.60276  127.60411  127.6044   127.60513
 127.60624  127.6065   127.60594  127.604095 127.60103  127.59965
 127.59992  127.59992  127.59962  127.59994  127.60091  127.602516
 127.60483  127.60613  127.606346 127.60615  127.605484 127.60524
 127.60545  127.605804 127.606316 127.606316 127.6057   127.60559
 127.60615  127.607    127.608246 127.60918  127.609665 127.61126
 127.61437  127.61633  127.616714 127.61716  127.61766  127.61754
 127.616455 127.61604  127.61667  127.61603  127.613434 127.611336
 127.61007  127.61028  127.612946 127.61474  127.615074 127.61644
 127.619606 127.62211  127.62336  127.62387  127.62301  127.62269
 127.623436 127.62462  127.62667  127.62722  127.624725 127.623375
 127.624405 127.62537  127.62617  127.62494  127.61913  127.618126
 127.62819  127.637146 127.64337  127.64512  127.635864 127.6288
 127.6273   127.62574  127.62402  127.61845  127.602425 127.58858
 127.580826 127.574814 127.573746 127.57142  127.56525  127.560585
 127.5606   127.56126  127.56403  127.56706  127.57089  127.5744
 127.576805 127.57803  127.57508  127.57537  127.587975 127.60455
 127.636795 127.66293  127.66376  127.65202  127.586    127.54949
 127.646355 127.73665  127.795975 127.8542   127.9069   127.95505
 127.97961  127.97481  127.80909  127.66546  127.649315 127.639496
 127.66809  127.6845   127.62252  127.568886 127.57235  127.57474
 127.56935  127.56561  127.57466  127.58381  127.593735 127.603615
 127.6131   127.62243  127.630196 127.63766  127.64196  127.64622
 127.64971  127.65325  127.65743  127.66152  127.66447  127.66731
 127.66866  127.66976  127.666595 127.66339  127.65941  127.655396
 127.65075  127.64597  127.63851  127.63123  127.63096  127.631294
 127.66137  127.690994 127.68572  127.6809   127.742004 127.8031  ], all between 126-128 most of the time]

**Comment by backseason** [comment]
I guess you have loaded the wrong pretrained model.
The missing keys are random initialized, which is why you got predictions around 127.
If you are going to use the jointly trained model, you'll need to use the scripts begin with `joint_`.

**Comment by AthaSSiN** [comment]
This solved the issue! Thank you so much
