### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by Goru1890** [backseason/PoolNet#62]
I'm getting back a cuda error:

RuntimeError: CUDA out of memory. Tried to allocate 1.19 GiB (GPU 0; 10.76 GiB total capacity; 7.49 GiB already allocated; 1.14 GiB free; 779.64 MiB cached)

My Pytorch version is 1.3.1

UPDATE:
I'm ussing CUDA 10.2, Pytorch 0.4.1 is incompatible with CUDA 10.2

**Comment by backseason** [comment]
I guess PyTorch version should not cause this error. As the error said, did your gpu have enough free memory at that time or was your input image too big?

**Comment by Goru1890** [comment]
The images are really big 5472 x 3648.
Should I resize them?

**Comment by backseason** [comment]
Yes, you should resize them until the code can run on your GPU.

**Comment by Goru1890** [comment]
Where in your code is the image input? So I can pass every image through a resize function.

**Comment by backseason** [comment]
You can find them here: https://github.com/backseason/PoolNet/tree/master/dataset

**Comment by Goru1890** [comment]
Thank you for you help.
