### ISSUE TITLE
The size of the gt is mismatch with the size of the results.

### ISSUE THREAD

**Issue by djl0912111** [backseason/PoolNet#67]
Sorry to bother you.
I have just found that the results in DUTS-TE have several pictures mismatch.
for example,  the size in the picture which named ILSVRC2012_test_00036002.png in the DUTS-TE-MASK is 400*266, however, corresponding one in the run-0-sal-d which named ILSVRC2012_test_00036002_sal_fuse.png have the size of 400*308.
Because I want to calculate the MAE, the problem above restrict me, and I have found it is not the only one in the results file.
Hope your reply, thank you.

**Comment by backseason** [comment]
You can resize the predicted map to the same size as the gt. The performance will be nearly the same.

**Comment by djl0912111** [comment]
Thanks a lot. And I have an other pproblem in evaluation.
I follows your repo in other issues getting an url for evaluation,like this  https://github.com/Pchank/caffe-sal.
However, I found the maxF which calculated is different with the results in the paper. I think it may calculate the average F-measure.
Do you have any other code for Max F-measure.
Sorry to bother you. Thanks a lot. 
Hope your reply.
Best wishes!

**Comment by backseason** [comment]
You can use the code mentioned here: https://github.com/backseason/PoolNet#update ,
which should produce the same evaluation results as reported in the paper.

**Comment by djl0912111** [comment]
Thanks a lot. Actually, I have tried many times, both in windows and in linux. I still can't install it.
Did you evaluate the results using this mode? Did I have any other choice.
It 's very kind of you,I really bother you a lot.o(╥﹏╥)o

**Comment by backseason** [comment]
Yes, that's the code that I've been using. My environment for evaluation is Ubuntu 16(18).04 and Python 2.7.

**Comment by djl0912111** [comment]
I’ll try it in python2.7 ! Thank you very much! 
Peace & Love!
