### ISSUE TITLE
Issue in reusing the pretrained models

### ISSUE THREAD

**Issue by HarshitSinghChhabra** [backseason/PoolNet#76]
Hi, a very great project. When I try to use "PoolNet-ResNet50 w/ edge model" provided in the drive to test on my own data using -e mode by properly adding the files and making a .lst file, it shows incompatible shape in checkpoint and current model.
Pasting the Error message - 
RuntimeError: Error(s) in loading state_dict for PoolNet:
	Unexpected key(s) in state_dict: "block.0.block_in1.0.weight", "block.0.block_in2.0.weight", "block.0.block_mid1.0.0.weight", "block.0.block_mid1.0.1.weight", "block.0.block_mid2.0.0.weight", "block.0.block_mid2.0.1.weight", "block.0.block_out.0.weight", "block.1.block_in1.0.weight", "block.1.block_in2.0.weight", "block.1.block_mid1.0.0.weight", "block.1.block_mid1.0.1.weight", "block.1.block_mid2.0.0.weight", "block.1.block_mid2.0.1.weight", "block.1.block_out.0.weight", "block.2.block_in1.0.weight", "block.2.block_in2.0.weight", "block.2.block_mid1.0.0.weight", "block.2.block_mid1.0.1.weight", "block.2.block_mid2.0.0.weight", "block.2.block_mid2.0.1.weight", "block.2.block_out.0.weight", "block.3.block_in1.0.weight", "block.3.block_in2.0.weight", "block.3.block_mid1.0.0.weight", "block.3.block_mid1.0.1.weight", "block.3.block_mid2.0.0.weight", "block.3.block_mid2.0.1.weight", "block.3.block_out.0.weight", "fuse.trans.0.weight", "fuse.trans.0.bias", "fuse.trans.1.weight", "fuse.trans.1.bias", "fuse.trans.2.weight", "fuse.trans.2.bias", "fuse.trans.3.weight", "fuse.trans.3.bias", "fuse.fuse.weight", "fuse.fuse.bias", "edgeinfo.trans.0.weight", "edgeinfo.trans.2.weight", "edgeinfo.trans.4.weight", "edgeinfo.trans.6.weight". 
	
size mismatch for score.score.weight: copying a param with shape torch.Size([1, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 128, 1, 1]).

Can you please tell why this is happening. Thanks

**Comment by HarshitSinghChhabra** [comment]
Issue Resolved. It was due to GPU specification on Colab

**Comment by malcolmagius19** [comment]
Hi, can I ask how you solved the issue if you remember please? Did you have to run the model on your machine locally or were you able to run it through Colab still?
Thanks
