### ISSUE TITLE
Could you provide the trained model ?

### ISSUE THREAD

**Issue by happycoding1996** [backseason/PoolNet#9]
Thanks for your great work!

I want to directly test your model on my personal dataset but it seems like only pretrained backbone is provided.

Could you provide the trained entire model with ResNet50 backbone ? 

Thank you ~

**Comment by backseason** [comment]
The pretrained models are actually provided.
You can find them in the readme.md file (https://github.com/backseason/PoolNet#6-pre-trained-models-pre-computed-results-and-evaluation-results).

**Comment by happycoding1996** [comment]
@backseason Thank you ! My bad, I did not go down for the trained model.
